name: Test
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.22.3"
        mysql:
          - "mysql:5.7"
          - "mysql:8.0"
    name: Build
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    services:
      db:
        image: ${{ matrix.mysql }}
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: mysqlbatch
          MYSQL_DATABASE: mysqlbatch
          MYSQL_USER: mysqlbatch
          MYSQL_PASSWORD: mysqlbatch
          TZ: Asia/Tokyo
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - run: go test -race ./...
